In [1]:
import pandas as pd

# Leer el archivo CSV como DataFrame
df = pd.read_csv('dataset_ejemplo_digidata.csv')

df

,idVenta,fecha,hora,sucursal,producto,precioU,cantidad,importe,metodoPago,usuario
0,0,01/01/2022,18:17,sucursal 2,producto 5,2000,1,2000,otro,usuario 2
1,1,02/01/2022,10:07,sucursal 3,producto 6,3500,2,7000,tarjeta de debito,usuario 1
2,2,03/01/2022,17:51,sucursal 1,producto 7,1800,5,9000,codigo QR,usuario 5
3,3,04/01/2022,13:56,sucursal 2,producto 7,1800,1,1800,tarjeta de credito,usuario 1
4,4,05/01/2022,16:07,sucursal 3,producto 3,1500,1,1500,otro,usuario 5
...,...,...,...,...,...,...,...,...,...,...
1996,1996,20/06/2027,12:45,sucursal 1,producto 2,2500,4,10000,otro,usuario 2
1997,1997,21/06/2027,18:19,sucursal 3,producto 8,2700,1,2700,codigo QR,usuario 5
1998,1998,22/06/2027,20:04,sucursal 3,producto 2,2500,3,7500,codigo QR,usuario 4
1999,1999,23/06/2027,15:42,sucursal 1,producto 2,2500,1,2500,codigo QR,usuario 1
2000,2000,24/06/2027,10:44,sucursal 2,producto 3,1500,1,1500,tarjeta de debito,usuario 4